const endpoints = {
  sequences: '/sequences',
  sequence: (id) => `/sequences/${id}`,
  sequenceTextFile: (id) => `/sequences/${id}/text_file_sequence`,
  sequenceChangeAnnotation: (id) => `/sequences/${id}/change_annotation`,
  sequenceCloningStrategy: (id) => `/sequences/${id}/cloning_strategy`,
  sequenceChildren: (id) => `/sequences/${id}/children`,
  sequenceLines: (id) => `/sequences/${id}/lines`,
  sequenceChangeCircularity: (id) => `/sequences/${id}/change_circularity`,
  sequencePrimers: (id) => `/sequences/${id}/primers`,
  sequenceSequencingFiles: (id) => `/sequences/${id}/sequencing_files`,
  sequenceSearch: '/sequences/search',
  sequencesValidateUpload: '/sequences/validate-upload',
  sequencesBulk: '/sequences/bulk',
  sequencingFileDownload: (id) => `/sequencing_files/${id}/download`,
  sequenceSequencingFileDelete: (sequenceId, fileId) => `/sequences/${sequenceId}/sequencing_files/${fileId}`,
  postSequence: '/sequences',
  primers: '/primers',
  primersValidateUpload: '/primers/validate-upload',
  primersBulk: '/primers/bulk',
  primer: (id) => `/primers/${id}`,
  primerTemplateSequences: (id) => `/primers/${id}/sequences`,
  postPrimer: '/primers',
  lines: '/lines',
  line: (id) => `/lines/${id}`,
  lineChildren: (id) => `/lines/${id}/children`,
  lineTags: (id) => `/lines/${id}/tags`,
  inputEntityTags: (id) => `/input_entities/${id}/tags`,
  postLine: '/lines',
  tags: '/tags',
  tagPost: '/tags',
  tagUnlinkLine: (lineId, tagId) => `/lines/${lineId}/tags/${tagId}`,
  tagUnlinkInputEntity: (inputEntityId, tagId) => `/input_entities/${inputEntityId}/tags/${tagId}`,
  sequenceSamples: '/sequence_samples',
  postSequenceSample: '/sequence_samples',
  sequenceSample: (uid) => `/sequence_samples/${uid}`,
  authToken: '/auth/token',
  authRegister: '/auth/register',
  authMe: '/auth/me',
  workspaces: '/workspaces',
  postWorkspace: '/workspaces',
  workspace: (id) => `/workspaces/${id}`,
  templateSequences: '/template_sequences',
};

export default endpoints;
